### ISSUE TITLE
Decide where Distances should be located

### ISSUE THREAD

**Issue by Thanathan-k** [gipplab/MathMLSim#9]
Currently Distances is only copied code of Mathopshere. If the code is edited at one point, the two version might differ which can lead to problems.

The code already diverged recently: https://github.com/ag-gipp/MathMLSim/blob/master/src/main/java/com/formulasearchengine/mathmlsim/Distances.java#L40
vs
https://github.com/ag-gipp/MathMLSim/commit/e86d7aba75afd7bfe3a5abbd7b5df89a8c6c3092#diff-e2559fcca35ed055dedf08363f9b7a38R34

**Comment by vstange** [comment]
@physikerwelt remove it from mathosphere and just link to mathmlsim?

**Comment by physikerwelt** [comment]
@vstange good idea. Could you make a PR?

**Comment by vstange** [comment]
@physikerwelt The mathpd package contains some dependencies that I did not know before. If we combine the classes on MathMLSim, I would have to abstract or drag the pojos like ArvixDocument into MathMLSim. Here I would act according to what you like more?

Nevertheless, I'll do first a merge for MathMLSim, which will make everything smooth and then the one for mathosphere.

**Comment by physikerwelt** [comment]
> @physikerwelt The mathpd package contains some dependencies that I did not know before. If we combine the classes on MathMLSim, I would have to abstract or drag the pojos like ArvixDocument into MathMLSim. Here I would act according to what you like more?
Let's discuss that here https://github.com/ag-gipp/mathosphere/issues/167

> Nevertheless, I'll do first a merge for MathMLSim, which will make everything smooth and then the one for mathosphere.

Where and when?

**Comment by physikerwelt** [comment]
@vstange what is the status about this ticket. Is it still relevant? Should it be moved to JIRA?

**Comment by physikerwelt** [comment]
@AndreG-P, do we have an approach for that? The problem was (if I remember correctly) that sonatype was somehow dysfunctional?

**Comment by AndreG-P** [comment]
@physikerwelt This project is part of MathMLTools: https://github.com/gipplab/MathMLTools/tree/master/mathml-similarity
And mathosphere imports MathML tools. 

If you mean the issue with deploy to maven central, I dont really know what the issue was.

**Comment by physikerwelt** [comment]
So the most recent version is this repository. Thank you
